container_commands:
  01_setup_permissions:
    command: |
      chmod -R 775 /var/app/current/storage /var/app/current/bootstrap/cache
      chown -R webapp:webapp /var/app/current/storage /var/app/current/bootstrap/cache
  02_migrate:
    command: "php artisan migrate --force"
